# Generated by Django 5.2 on 2025-04-25 07:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='颜色名称')),
                ('code', models.CharField(default='', max_length=10, verbose_name='颜色代码')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='材质名称')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='尺码规格')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='状态ID')),
                ('name', models.CharField(max_length=5, verbose_name='状态名称')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='衣服类别')),
                ('image', models.ImageField(max_length=1000, null=True, upload_to='', verbose_name='图片')),
                ('comments', models.CharField(default='', max_length=50, verbose_name='说明')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('rfid', models.IntegerField(null=True, unique=True, verbose_name='RFID')),
                ('name', models.CharField(max_length=30, verbose_name='衣服名称')),
                ('price', models.SmallIntegerField(verbose_name='进货价格')),
                ('is_printed', models.BooleanField(default=False, verbose_name='是否有效')),
                ('is_reprinted', models.BooleanField(default=False, verbose_name='是否重打')),
                ('indate', models.DateField(default=datetime.datetime.today, verbose_name='入库日期')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('comments', models.CharField(max_length=200, verbose_name='备注')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.color', verbose_name='颜色')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.material', verbose_name='材质')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.size', verbose_name='尺码')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.status', verbose_name='状态')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.type', verbose_name='种类')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Reprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.IntegerField(unique=True, verbose_name='RFID')),
                ('reason', models.CharField(max_length=100, verbose_name='补打原因')),
                ('image', models.ImageField(max_length=1000, null=True, upload_to='', verbose_name='上传图片')),
                ('reprint_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='补打时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes', verbose_name='衣服id')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, unique=True, verbose_name='批量名称')),
                ('name', models.CharField(max_length=30, verbose_name='衣服名称')),
                ('color', models.CharField(max_length=5, verbose_name='衣服颜色')),
                ('material', models.CharField(default='全棉', max_length=15, verbose_name='材质')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归属人')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes', verbose_name='衣服id')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.size', verbose_name='尺码')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='', max_length=12, unique=True, verbose_name='电话')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='吊牌', max_length=20, unique=True, verbose_name='打印模板名称')),
                ('body', models.TextField(verbose_name='主体内容')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='仓库名称')),
                ('address', models.CharField(max_length=100, verbose_name='仓库地址')),
                ('coord', models.JSONField(default=dict, max_length=100, verbose_name='经纬度坐标')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='归属人')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField(verbose_name='销售价格')),
                ('reason', models.CharField(max_length=100, verbose_name='退货原因')),
                ('image', models.ImageField(max_length=1000, null=True, upload_to='', verbose_name='上传图片')),
                ('return_time', models.DateTimeField(auto_now_add=True, verbose_name='退货时间')),
                ('handled', models.CharField(max_length=8, verbose_name='经手人')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes', verbose_name='衣服id')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.warehouse', verbose_name='退货仓库')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.warehouse', verbose_name='仓库名称'),
        ),
    ]
