# Generated by Django 5.2 on 2025-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='说明'),
        ),
    ]
